### creating a comment
POST http://localhost:4001/posts/1/comments
content-type: application/json

{
    "content": "Hii I'm a comment"
}

### getting comments
GET http://localhost:4001/posts/b73d1411-f4f1-43f2-a82c-d9d72d8f75a0/comments
